In [1]:
import pandas

In [4]:
data_csv = pandas.read_csv('Tweets.csv')

In [12]:
data_csv[data_csv.airline == "Delta"]

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
6746,5.703093e+17,positive,0.6469,NaN,NaN,Delta,NaN,jaxbra,NaN,0,@JetBlue Yesterday on my way from EWR to FLL j...,NaN,2015-02-24 11:48:38 -0800,"east brunswick, nj",Atlantic Time (Canada)
6747,5.703093e+17,neutral,0.6869,NaN,NaN,Delta,NaN,Oneladyyouadore,NaN,0,@JetBlue I hope so because I fly very often an...,NaN,2015-02-24 11:48:29 -0800,Georgia,Quito
6748,5.703085e+17,neutral,1.0000,NaN,NaN,Delta,NaN,Oneladyyouadore,NaN,0,"@JetBlue flight 1041 to Savannah, GA",NaN,2015-02-24 11:45:20 -0800,Georgia,Quito
6749,5.703078e+17,negative,1.0000,Flight Attendant Complaints,0.6522,Delta,NaN,Oneladyyouadore,NaN,0,"@JetBlue They weren't on any flight, they just...",NaN,2015-02-24 11:42:34 -0800,Georgia,Quito
6750,5.703054e+17,negative,1.0000,Bad Flight,1.0000,Delta,NaN,Oneladyyouadore,NaN,0,@JetBlue everyone is here but our pilots are n...,NaN,2015-02-24 11:32:49 -0800,Georgia,Quito
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8963,5.676673e+17,neutral,1.0000,NaN,NaN,Delta,NaN,BritishAirNews,NaN,0,"@JetBlue CEO weighs profits, flyers - @Chronic...",NaN,2015-02-17 04:50:05 -0800,UK,Sydney
8964,5.675900e+17,negative,1.0000,Can't Tell,0.6503,Delta,NaN,nesi_1992,NaN,0,@JetBlue is REALLY getting on my nerves !! ðŸ˜¡ðŸ˜¡ ...,NaN,2015-02-16 23:43:02 -0800,undecided,Pacific Time (US & Canada)
8965,5.675883e+17,neutral,1.0000,NaN,NaN,Delta,NaN,JetBlueNews,NaN,0,@JetBlue's new CEO seeks the right balance to ...,NaN,2015-02-16 23:36:05 -0800,USA,Sydney
12038,5.702945e+17,negative,1.0000,longlines,0.4686,Delta,negative,DetroitRonin,Customer Service Issue,0,@DeltaAssist now at 57 minutes waiting on Silv...,NaN,2015-02-24 10:49:27 -0800,Thataway,Eastern Time (US & Canada)
12039,5.687577e+17,negative,0.7991,Can't Tell,0.6423,Delta,negative,ConnieBowman4,Customer Service Issue\nCan't Tell,0,@DeltaAssist what I have to say is more than 1...,NaN,2015-02-20 05:02:50 -0800,NaN,NaN